### ISSUE TITLE
Not urgent - chem lab facilitator guide, commands

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#10]
I don't think those commands out of facil guide work, but I don't know if we need them.
If the alarm is on, use “/101 –pull_alarm” or “/-111 @disable_Alarm”  to disable alarm

**Comment by raynaglieri** [comment]
Those commands are outdated. Please use "/101-alarm-on" and "/101-reset" or "/101-alarm-off". "/20001-reset" will reset the whole lab including the fire alarm.
