### ISSUE TITLE
Prob. solving 1 -> Bugs -> High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#103]
Ray, 

I did some quick testing of prob. solving 1 today as Zhaihuan had a trainee but didn't go till the end. Now, Zhaihuan said they encountered double messages from NPCs (saying things they supposed to say but twice in a row) on G16, G 17, G19.

Could you looking into it? https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=922882453

**Comment by raynaglieri** [comment]
I'll look into it now.

**Comment by raynaglieri** [comment]
Okay, it seems to be working properly now.
