### ISSUE TITLE
Teach2 -> Bugs -> High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#104]
Ray,
I found some bugs in teach 2 (Zhaihuan too). there were several cases when NPCs repeat things twice - but it is not my concern.
My concern is G10 - sentence in red, G17 - correct the text to what is in red and I'm not sure trainee got a notecard, G21 - in red, there was nothing from NPC that would indicate disappointment/sadness, G24, G25.
We have a command /720001-ad_complex as a part of the G24-G25 sequence and it didn't work for Zhaihuan on Monday or for me today.

https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=106009112

**Comment by raynaglieri** [comment]
The issue was a duplicate NPC, so no NPC2 was active and instead we had duplicate NPC3s. Also, the note card appears to be working properly after a few test.
