### ISSUE TITLE
Push Xin's script to the beginning of the physics lab

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#11]

**Comment by raynaglieri** [comment]
Updated script is incorrect. On line 472 from state s13 there is no valid transition for "no". This is causing a compilation error and the script cannot be used.

**Comment by MariyaPa** [comment]
Hmm...it's a generator. In my text file s13 transits to s14 on yes and to s15 on no. I checked Xin's file, yes, it breaks on line 472
