### ISSUE TITLE
Phys lab 3 -> Bugs -> Medium-High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#111]
Ok. First of all, this didn't work:

19G: -adnc_mean.r1
	 -adnc_mean.r2
	 -adnc_mean.nc

This worked 18G: -adnc_mean and then - nothing. And you don't need to have a separate command for a notecard. Both yes and no responses get the notecard as i remember

Second, could we have offsets for textures on walls? some margins? Because it looks a bit funky as is

![image](https://user-images.githubusercontent.com/36109730/50017800-38a2b080-ff9b-11e8-8641-29f83d8a0db4.png)
 
Cheers

**Comment by raynaglieri** [comment]
Please update the facilitator protocol to match these command updates:-
18G: -ad_mean
19G: -ad_mean.r1
	 -ad_mean.r2
         -ad_mean.nc

**Comment by MariyaPa** [comment]
Ray, did you update the script?
As now even the first command - 18G: -ad_mean doesn't work!

**Comment by MariyaPa** [comment]
Ray,


Did you update the script?


It deosn't work - at all, the rest of the commands is ok.


Mariya


--

Mariya Pachman
Post-doctoral Fellow, MILE project

College of Education
Stone bldg., 1208A
Tallahassee, FL 32306-4453
Florida State University
Honorary Research Fellow
Macquarie university, australia

E-mail: mpachman@fsu.edu

<mailto:mariya.pachman@gmail.com>

________________________________

**Comment by raynaglieri** [comment]
Not sure what happened but, NPC 7 needed to have their script reset.
