### ISSUE TITLE
Finish development of Teach Adaptively

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#12]
Ray, somehow I thought that all the changes we made in a design doc were implemented. They are not. I put them all in red in a design doc
1) Green messages "Lecture Continues" and such do not appear.
2) Gestures - I had a column in design doc since 1/17 just to make the choice of gestures easier, but if there are no gestures on place that a problem.
3) Back channel - we still have all these back responses from NPCs like 20, 5 or whatever to indicate that they are listening.
4) Green message "Instructional Game" appeared one row before of where it should have been.
5) Notecard Leanring Goals came out blank.
6) Instructional game itself. I remember you have updated the first question to be a yes or no. But today when we were doing the testing the old version that starts with When came up and there was no way to reset it (we couldn't get to blue boxes).
7) The timing. Blue boxes need to have a longer delay after NPCs movements / words.
8) I couldn't see all the NPCs, only 6 and one as a red cloud. But BJ and Zhaihuan had all of them there.

I think that's it. We will upload videos to the Drive and give you a link.

**Comment by MariyaPa** [comment]
![snapshot missing npc_001](https://user-images.githubusercontent.com/36109730/36277487-10092eee-125f-11e8-9558-54e9da0914d0.jpg)

**Comment by raynaglieri** [comment]
Ready for full scenario testing.
