### ISSUE TITLE
A little things about Chem lab.

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#13]
1) BJ had an issue with How would you demonstrate experiment procedures? blue box. He took some time to think, then when he started typing this answer the box evidently reloaded or something like that, but it erased all his wrote in the middle of his second sentence.
2) Mary Smith NPC - she is sitting ok during the intro but is standing too high during all the experimental scenarios (see below). And by the way, this happened only after the last week server resets. I think she was alright before that.
![chem lab](https://user-images.githubusercontent.com/36109730/36279988-db05634a-1266-11e8-9b6f-41c53d3d35c5.jpg)

**Comment by raynaglieri** [comment]
Okay, I'll look into these issues. Although for the first one, that behavior is defined. I can increase the timeout time of the blue boxes if you would like.

**Comment by MariyaPa** [comment]
Yes, please, do. I can give you a link to watch his recording but that's exactly what one sees - he starts typing and in the middle of the second phrase his test disappears - the same box (box reloads?).

**Comment by raynaglieri** [comment]
Okay, I've fixed and updated.
