### ISSUE TITLE
Teach adaptively -> Bugs (animations)  -> medium

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#16]
https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=1091213507

1. A trainee is able to get a hangout (H14) but when he drags it to NPC he gets a message "No space in the inventory". How do we deal with handouts?

2. G3, G5, G10, G12, G13, G14, G18, G22 - some animations are there, some are not. Please, check. If they are there, they don't last long enough for trainee to notice or don't stop at all. For example, G12 to G13. In G12 only 1 NPC stays bored, but it doesn't stop being bored with the next command. So, it messes up G13 as well. Please, fix

**Comment by MariyaPa** [comment]
Also, I changed a notecard text, G8. Link is the same, text is different.

**Comment by raynaglieri** [comment]
Some bugs are just a result of incomplete code I'm testing. Please wait until i've finished development before testing the whole scenario again.
