### ISSUE TITLE
Training Arena -> Bug? -> medium

### ISSUE THREAD

**Issue by ZhaihuanDai** [raynaglieri/MILE4STEM_FSU#17]
The drag and drop to change texture function only worked for Test User account, not for other facilitator accounts.

When facil 1, 3, and 4 tried to drag texture from inventory and drop it on the object (the one scripts attached to), an circle icon with a lock appeared. 

Below is the scripts used (could not attach the file, so I pasted scripts here)

// Created on 1/29/2017 By Raymond Naglieri.
// Description: update prim texture to nth inventory via the board_control_channel. Click on prim to remove all textures from inventory and clear the set one.
// 2/20/18: Updated for training arena. 
//		  : Added delete_all_other_contents function provided by, http://wiki.secondlife.com/wiki/LlRemoveInventory . This will clear the prims given textures if the prim is clicked on. 
string slide_texture;
integer MAX_SLIDE_COUNT = 5; 
integer board_control_channel = 36000;

// deletes all other contents of any type except the script itself
delete_all_other_contents()
{
    string thisScript = llGetScriptName();
    string inventoryItemName;
 
    integer index = llGetInventoryNumber(INVENTORY_ALL);
    while (index)
    {
        --index;        // (faster than index--;)
 
        inventoryItemName = llGetInventoryName(INVENTORY_ALL, index);
 
        if (inventoryItemName != thisScript)   
            llRemoveInventory(inventoryItemName);     
    }
}

display_slide(integer slide_number)
{
	if(slide_number >= 0 && slide_number <= MAX_SLIDE_COUNT)
	{
		slide_texture = llGetInventoryName(INVENTORY_TEXTURE, slide_number);
		llSetTexture(slide_texture, ALL_SIDES);		
		return;
	}		
}

default
{
	state_entry()
	{
		llListen(board_control_channel, "", NULL_KEY, "");
	}

	touch_start(integer num_detected) // touching the prim will remove textures. 
	{
		delete_all_other_contents();
		llSetTexture(TEXTURE_BLANK, ALL_SIDES);
	}

	listen(integer c, string n, key ID, string msg)
	{
		display_slide((integer)msg);
	}
}

**Comment by raynaglieri** [comment]
I've added support for this issue, check the training_arena folder for the updated script.
