### ISSUE TITLE
Training arena -> Development -> Medium

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#18]
Is there a way to create text chatgroups or multiperson chat (at least textual)?
![problems with multi-person interactions](https://user-images.githubusercontent.com/36109730/36568980-f40252ca-17f9-11e8-845f-e1a46970424b.jpg)

**Comment by raynaglieri** [comment]
closed wrong issue. sorry.

**Comment by raynaglieri** [comment]
Looking into how to add group support to our opensim server.
