### ISSUE TITLE
Explaining -> Design Change, more commands needed -> Urgent

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#19]
I have added whatever I could to the code, but I don't know how to add changes to -G7, G8, G9. Those are NOT A TEXT INPUT BOXES, trainee has to react orally or using a whiteboard. Facil should have 2 commands: first - to push the pop-up in G7, G8, G9; second - to enable feedback in H7, H8, H9 if needed. I7 also has a new green message that could appear together with G7 at the first command.

https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=403138377

**Comment by raynaglieri** [comment]
Fixed. Add an exclamation mark to the command to display feedback.
