### ISSUE TITLE
Exaplining -> Bugs -> Urgent

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#22]
Everything's ok. We have one disruptive student (John). :)
But... 1) when you were pushing in the last changes you didn't remove the previous version, so it gives doubles: All green messages for I3 are doubles.
 2) NPC in G4 needs a longer delay before she says thanks. 
3) I had to change a couple more words and created a new version - pull request.
4) I couldn't see all the students
![snapshot_001](https://user-images.githubusercontent.com/36109730/36864999-46473d22-1d5c-11e8-8ba4-075cc5ed737c.jpg)

**Comment by raynaglieri** [comment]
I've fixed issues 1 and 3. Issue 2 will require a little time. I can't reproduce 4, but this usually happens after a server reset. Always call the /20001-rest command before starting. This should fix the issue.

**Comment by raynaglieri** [comment]
Okay I've uploaded the updated scripts to the server. All issues in this ticket should be resolved.
