### ISSUE TITLE
 All Barbara's corrections for Physics Lab -> Bugs -> Urgent

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#23]
1) You have closed the issue but I don't have commands for new rows -22,23,24,25
2) I checked the Physics lab but it has this test student sitting in the air away from the rest.
3) On /20001-a_npcmeterbroken (H17) John didn't let me respond and gave me "I did it" about 50 times (full screen).
So I just think Physics Lab is not ready.

**Comment by raynaglieri** [comment]
Commands: 
-a_connect4voltage
-a_connect4current
-d_connect4voltage
-d_connect4current
-sb_npcmeasurevoltage (changes to second slide D29)

Removed test NPC(floating in the air),  fixing the error 3.
