### ISSUE TITLE
General(mainly for Training Arena)->Update->High

### ISSUE THREAD

**Issue by ZhaihuanDai** [raynaglieri/MILE4STEM_FSU#28]
Please update/finalize the "drag and drop" scripts to allow anyone can change the texture of objects

**Comment by raynaglieri** [comment]
script is done.

**Comment by ZhaihuanDai** [comment]
Tested with Facil1 and found unstable performance. 

It seems that there is some delay after reset and the delay time varies. I tested with two objects but they perform differently. Sometimes one performed well but the other didn't, sometimes both worked fine, sometimes delay for one was longer than the other, etc.. Pretty random.
