### ISSUE TITLE
Training arena (orientation video) -> Enhancement -> Medium

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#32]
When you have some time....As you, guys, have noticed, the orienation video text is missing some of the articles - I have made a copy of the original text, could you please check / correct it.

https://drive.google.com/open?id=1n-kadTTEfo73ZY5mdWFU2L2OESx0-Rt6bk8ZODTzr44

**Comment by raynaglieri** [comment]
I've made my changes in red. I only checked for grammar.
