### ISSUE TITLE
Physics Lab -> extend timeouts (bug?) -> High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#38]
Hi, Ray,

The Physics Lab testing today went well, blue boxes were corrected, some keywords changed. We had one  previous issue and one new:
1) Gender and audios. Susan's and Mary's audio files are male voice. Do you need spreadsheet cells number to correct them?
2) At F25 when Mary asked the question she timed out after that -  i mean she was not reacting on keywords, nor on something else (they are supposed to say "I've tried" it if it's not a keyword)

https://drive.google.com/open?id=1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE

But generally the Lab went well :)

**Comment by raynaglieri** [comment]
I'm still correcting the gender audio and I'll look into the second issue.

**Comment by raynaglieri** [comment]
I've fixed the issues. However, we may want to add more female voices. The variety is lacking.
