### ISSUE TITLE
Training arena -> Bugs? -> multicard giver questions

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#41]
Hi, Ray, 

We got a couple of strange situations today when testing multicard giver. NB: we had all the 13 notecards in as a sequence, TA notecard was there at the beginning. 
1) On one occasion it didn't find certain notecards but all of them were there, and then gave a weird "no inventory object" message right before green reshuffle message. 
2) On the other occasion it simply gave "no inventory object" message right before green reshuffle message. 
Otherwise, it works fine :)

![capture](https://user-images.githubusercontent.com/36109730/37930832-e407f93e-3111-11e8-8ec6-373e6113f3b1.PNG)

**Comment by raynaglieri** [comment]
I will try and recreate the issue. It may be related to white space in the DECK_ORDER_FILE

**Comment by raynaglieri** [comment]
For the first issue, the names in the DECK_ORDER_FILE didn't match exactly what was in the inventory. This was causing an error. For the second issue, extra white spice at the bottom of the DECK_ORDER_FILE was being counted as a notecard. I'll work on a solution to ignore white space, so you don't have to worry about it.

**Comment by raynaglieri** [comment]
Added support to ignore whitespace. Should work smoother now.
