### ISSUE TITLE
Training arena -> Bugs -> Fix before Wed., the 11th

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#46]
Allocate all multi-role scripts in machines to different command channels. We have machines on levels 2 (2 machines) and level 3 (2 machines)

**Comment by raynaglieri** [comment]
Okay each one now operates on a different control channel: 88000, 88001,88002, and 88003. I've labeled each one in the object description.

**Comment by MariyaPa** [comment]
Yes, you did. But it also erased all the role cards (which we have discovered this morning during the testing).

**Comment by MariyaPa** [comment]
Not really. I assumed all was done and ready. So, when we came I wanted them to try the machines - it was not working. Then, I inputted a reshuffling command - and it still wasn't working. Then, I finally took a look at the object and had to log in as test user to fix it.

**Comment by raynaglieri** [comment]
Okay, just to clarify, you had to manually re-add the notecards for each script?
