### ISSUE TITLE
Keywords for chemistry lab

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#5]
Ray, thank you for commands, but I actually couldn't fully test them as I don't remember what keywords you used, and you didn't implement the new keywords, so I was stuck. All keywords are in G-column in Activity Design https://docs.google.com/spreadsheets/d/1Zd2V-rm_jh7gpLCumZ6IJNWK82nxHQLqnPiPB1645Mo/edit#gid=1355088773
Tab: ChemLab updated 7/31

**Comment by raynaglieri** [comment]
I did implement they keywords, I’ll check the NPCs to ensure they all have the updated script

**Comment by raynaglieri** [comment]
Only one NPC had the updated key words. All are updated with the new script.

**Comment by MariyaPa** [comment]
Ray, there are a couple of things left. First, G59 in the design doc says "record the trainee response" - I assume we can save it as a part of the text chat. But can we save a voice file from trainee if he/she decides to answer using a mic?
Second, avatars were out of out of whack - standing in the middle of the tables and doing animations. I made sure that tables are not phantoms and moved their chairs a bit. Hope it will solve the problem.

**Comment by raynaglieri** [comment]
Hey Mariya, please be more specific, when and where, were the NPCs "out of whack"? If someone moves any of the tables, chairs, or even the whole floor; this will result in the NPCs not being where they are intended to go. Also, if you want me to add or fix something please submit it as an issue so I can better keep track of my tasks! Thanks!
