### ISSUE TITLE
Teaching adaptively -> Bug? -> Urgent

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#51]
I think we agreed that trainees have words in green to guide them, but I think you tied the following green message “It's a time to present your students with a prepared example” with the command  /20001-announce1! 
The message should be there even if the command is not used by facil. Could you fix it somehow?

**Comment by raynaglieri** [comment]
Okay,  /20001-announce1 will now say "It's a time to present your students with a prepared example." Currently, there is no clean and easy way to make the message appear automatically. We would need to define an automatic version of the scenario.  If we want to make that functionality a priority let me know.  I'm going to close the issue for now. Open a new ticket if you want to support an automatic scenario.
