### ISSUE TITLE
Begin development for problem solving lecture

### ISSUE THREAD

**Issue by raynaglieri** [raynaglieri/MILE4STEM_FSU#54]

**Comment by MariyaPa** [comment]
Hi, Ray, I have updated everything in the scenario and also tried to help with development a bit - you'll see. But I guess my solution is not complete - change of pictures should be command-driven like in the physics lab. So, I have uploaded all the textures in a new folder "Lecturing prob-solving".

**Comment by MariyaPa** [comment]
Hi, Ray, as you already know the scenario testing will take place on 22nd (or 24th). I have updated all the problems and uploded the textures and also tweaked the design doc and notecards. All ready for development now! Pay attention on column D. Let me know if you have questions.
