### ISSUE TITLE
Teaching adaptively -> Enhancement -> Urgent

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#56]
Replace the word NPCs with "students" in green messages and blue boxes
--

**Comment by raynaglieri** [comment]
I could not find any occurrences of this in any of the teaching adaptive scripts. Did you see "NPC" appear somewhere specific?

**Comment by MariyaPa** [comment]
That's a surpise! Cause I think Explaining starts with something like "Divide NPCs on two groups". But let me check Teaching Adpatively scenario for this.

**Comment by raynaglieri** [comment]
Ok that makes sense, the issue was labeled for teaching adaptively. I assumed you wanted it done for both, but didn't see an occurrence in the teaching adaptive lecture. I already fixed the explaining lecture, I just have to upload it.

**Comment by raynaglieri** [comment]
updated!
