### ISSUE TITLE
Finish development of Explaining for understanding (auto mode)

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#6]
Ray, please, check everything that is in red in this document https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=403138377 Lecture design - Explaining tab and implement it. Those are the changes I have included a long time ago, after our testing and it's still not done.

**Comment by raynaglieri** [comment]
I've overhauled this scenario to match our current command driven design. I've also removed movement as requested. I'll send a command list to you.
