### ISSUE TITLE
Chem lab -> Bug? -> High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#63]
Zhaihuan was right. I don't see the whole branch of the scenario in chem lab, F48 through F56. When they ask 3 questions in a row and trainee doesn't  do any  intervention, facil. should be able to manually start this instrucitonal sequence: F48-F54.
I thought we had it.

**Comment by raynaglieri** [comment]
I do not remember adding these and they are not present in the npc script. In fact, there are quite a bit of changes that are not supported. I'll look into these now.

**Comment by MariyaPa** [comment]
I don't know if it is related to this thing with changing scenario but if you notice Susan Davis says "Excuse me" but then doesn't respond to her name and a strange
![image](https://user-images.githubusercontent.com/36109730/40882317-4c664830-66ac-11e8-9514-690cd700fe66.png)

**Comment by raynaglieri** [comment]
I have not received the updated NPC script and have not finished the scenario script. So this issue is unrelated to the new updates.  I'll look at the script now, but I'm unsure what would cause this to be a new issue.

**Comment by raynaglieri** [comment]
It looks like you entered the -npcs2 command before completing the sequence with the Susan Davis NPC. As a result, Susan Davis stopped her interaction. The green message, "npc-202-name_detected", is just a debugging message that I'll disable.

**Comment by MariyaPa** [comment]
Yes, but the problem is - our test user inputted Susan's name twice as you see and no response from her but the next npc started raising her hand.

Mariya

PS. It's not that important at the moment. Problem-solving is probably more important, but we still have 4 test users to schedule for chem. Lab.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MariyaPa** [comment]
Ok, I have run the sequence myself and was not able to replicate an issue with Susan - probably just a timeout. But I still got "npc-202-name_detected" message both time even though the seqiuence with Susan was finished. 
Btw, what are the keywords for -npcs2 scenario? 2 of the following keywords - “absorb”, “neutralize”, “baking soda”, “cold water”, “neutralize”? What about “sodium bicarbonate”,  “safety”?

**Comment by raynaglieri** [comment]
General key words : "absorb" - will elicit a follow up question .
specific key words : "safety", "baking soda", "sodium bicarbonate", "neutralize" - two of these will complete interaction.
