### ISSUE TITLE
Problem-solving -> Changes to scenairo /Enhancements -> High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#64]
Changes to scenario: G5 and H5; H19. Then, if you could use animations from K6 and K7 for the corresponding lines of the scenario it would probably look more realistic too.

**Comment by raynaglieri** [comment]
Okay, the updates are up. I've attached an updated command list. 
[PSL_commands_05301018.pdf](https://github.com/raynaglieri/MILE4STEM_FSU/files/2055508/PSL_commands_05301018.pdf)
