### ISSUE TITLE
Chem lab -> bug -> medium

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#68]
1) Disappearing text in blue box – disappears before trainee manages to click Submit but the blue box is still there (double box? didn’t we have a similar prob in Physics lab?). For “How would you demonstrate the experiment procedures?” box. For debriefing: “If you were to teach this lab again what would you do to prevent a similar situation from happening again?”

2) Please, don't forget to add animations

3) Question: Does fire alarm sound automatically on command or does it only sound when trainee says "pull fire alarm"?

**Comment by raynaglieri** [comment]
1. I'm extending the time to 60 seconds. Let me know if you would like a specific time. I'm still having upload issues independent of my location, so please be patient. 
2. I'm currently adding animations as previously stated.
3. You can either click the fire alarm to trigger it or the trainee must say "pull fire alarm." There is no public command currently implemented.
