### ISSUE TITLE
Finish Physics Lab -> Development -> Medium?

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#71]
1) Remove a "test" student John Smith on a side chair.
2) Create facil channel
3) Make sure animations are working - students are moving their hands when they "doing" experiments. 
4) Implement all keywords (in facil protocol in red-> https://docs.google.com/document/d/1m1uJKG46HBdX1vEx5HmV0ZxHN9iom4pBI85P8JsWlqs/edit)

**Comment by raynaglieri** [comment]
1. I deleted the npc so it should not be a reoccurring issue .
2. What do you mean by facil channel? Do you mean Facilitator Registration? That issue is already open.
3. Animations seem to working as deaigned. Could you elloborate on the issue? 
4. I'll add the updated keywords.

**Comment by MariyaPa** [comment]
2. Yes, I mean the ability of Facil to see what trainee sees, blue boxes (like in our lecture rooms).
3. In regard to animations - when NPCs start "conducting experiments" after the intro is over, it is not as visible as, say, in Chem. lab. Could we do something about it?
4. Yes, keep keywords that are there already and add those in red too.
