### ISSUE TITLE
Chem Lab -> Bugs -> Medium

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#72]
Ray, we were testing the chem lab today and I don't know why but a half of the commands are not working! Actually, /20001-a_ph1 
/20001-a_ph2
/20001-a_ph3
/20001-a_spill
/20001-a_fired
/20001-d_fireout

are the only ones that are working!
NPCs animations are working fine, though.

So, are you in the middle of developing something?

Thank you,
Mariya

**Comment by raynaglieri** [comment]
fixed.

**Comment by MariyaPa** [comment]
Ray, now 
/20001-a_fired doesn't work!
And yes, their exit is inefficient.
![screenshot 2018-07-13 17 33 49](https://user-images.githubusercontent.com/36109730/42715088-5537e20c-86c3-11e8-8411-30f6e98bcc53.png)

**Comment by raynaglieri** [comment]
Thats not a valid command, and I'll open up a issue for fixing the movement.

**Comment by raynaglieri** [comment]
I think the command you want is -a_fire

**Comment by raynaglieri** [comment]
The npc paths have been updated, they should now exit properly.
