### ISSUE TITLE
Office hours -> Development -> Medium

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#75]
1) Fix the gender
2) 
![image](https://user-images.githubusercontent.com/36109730/43166670-26f1651c-8f65-11e8-9392-5c6577f10822.png)
Replace "teach a Lecture to the students" to "have an Office hour"
3) I made changes in H5, they are in red. https://docs.google.com/spreadsheets/d/1Zd2V-rm_jh7gpLCumZ6IJNWK82nxHQLqnPiPB1645Mo/edit#gid=2126527670
4) Can we make a rude student to "disappear" instead of walking away? As in H6?
Otherwise - it is a lot of work. Wow!

**Comment by raynaglieri** [comment]
updated!
