### ISSUE TITLE
Moving prob-solving to CHEM -> Development -> High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#80]
Hi, Ray,

I guess one more thing that we didn't discuss while you were there is moving prob.-solving lecture on CHEM island so that each experimental group had everything on the same island. I set up a classroom and copied what I could but not the main scripts.

Landmark for this is: new prob-solving on CHEM

1. Could you make this new classroom work?
2. Yes, and then you'll have to update a copy of an island again to have everything on training 2 as well.

Let me know if you have questions.

It's one of the priorities to be done before 08.20.

**Comment by raynaglieri** [comment]
If the new classroom is on FSUCS CHEM, I can easily duplicate it on any island. Which Islands would you like me to overwrite?

**Comment by MariyaPa** [comment]
A new classroom is on CHEM but it is in the bldg. we have not been using before. All I need you to do is to include the scripts, facil channel. I have already copied, NPCs and everything on the lecturer's table. 

Then, when you set this classroom up -> update the copy of CHEM which we have for training 2. Does it make sense?

Mariya

**Comment by MariyaPa** [comment]
1) Yes, to the new bldg. in CHEM.
2) No, you don't need to update CHEM2 but training 2, because training 2 is adirect copy of CHEM... :)

**Comment by raynaglieri** [comment]
Okay, everything should be updated. I also added a facil feedback channel and a scenario offset. Use channel 420001 for commands.
