### ISSUE TITLE
Chem lab -> Bug / Movement -> Urgent

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#81]
I know you were updating coordinates for them, but they still didn't all leave - a half didn't leave.

![chem testing](https://user-images.githubusercontent.com/36109730/43730390-28785576-9979-11e8-9acc-dce451ce900e.jpg)

**Comment by raynaglieri** [comment]
Things were moved in the lab then. Their coordinates are hard coded, and do not change. I'll update them with new coordinates ASAP.

**Comment by raynaglieri** [comment]
I've re-updated the coordinates and the NPCs now exit the classroom properly. We should keep an eye out for issues like this when the server resets.I know we've had some issues with the shifting of objects.
