### ISSUE TITLE
Office hour -> Bug -> Important

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#82]
disruptive student who is supposed to sit in a chair on 
/120001-dm_begin
doesn't sit in a chair
and when he is supposed to come close and ask question on
/120001-am_toolong
he jumps on a first floor instead.
Island- training2 (but I assume it is the exact copy of CHEM)

**Comment by raynaglieri** [comment]
It is a copy, but all keys are different. Its working now that I've updated the script with the new chair key.
