### ISSUE TITLE
Chem lab -> Bug movements and gender -> Medium

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#83]
1) Their gender was not always right. Fengfeng thinks maybe you could show us with Zhaihuan how to correct it.
![bug mov gender](https://user-images.githubusercontent.com/36109730/43966908-1e2d8b52-9c91-11e8-9cc5-8a674a5839d4.jpg)
2) And John Smith doesn't go straight to alarm
![john smith](https://user-images.githubusercontent.com/36109730/43966943-3a6dd290-9c91-11e8-9a9f-8d1b36e11b65.jpg)
And doesn't exit the lab - you see his name - that's where he stays - in the center.

**Comment by raynaglieri** [comment]
It's strange that the genders changed, the names and app file are static. Did anyone update them?
I'll look into why John Smith is not exiting/Moving. There may be a hidden object  in his way.

**Comment by MariyaPa** [comment]
It was on training2 island (copies might not be exactly copies, you know) ;)

**Comment by raynaglieri** [comment]
Well there were issues again on CHEM1 that I just fixed. I think this is due to me resetting the server.

**Comment by raynaglieri** [comment]
Okay I've fixed the issue, John Smith never had exit coordinates for the fire emergency so I had to add them. The other movement issues I'm unsure about, sometimes they work and sometimes they don't. Since they are timer based, it could be a latency issue combined with the server reset issue.
