### ISSUE TITLE
Not really an issue - I just need to know where to go to change the text in Teach Adaptively

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#9]
Zhaihuan shortened text for some of the Teach Adaptively pop-ups and dialogues. It is in the design doc, column K. It is a no-brainer and I could change the text. But I need to know where to find a script to implement these changes. I promise not to touch anything else. :) I know it's somewhere in a hidden object as you do.

**Comment by raynaglieri** [comment]
Hey Mariya, I've added the script to the repository if you want to try and change it here: **MILE4STEM_FSU/adaptive_teaching_lecture/facil_adaptive_teaching.lsl** . You can download it and modify it. The dialogues are located at the top of the script in string variables called d_i__msg_n_ where 'i' and 'n'  are integers. So the first dialogue string would be d1_msg1. Once you've made the changes, send them to me via email and I will check it. Thanks, Ray

**Comment by raynaglieri** [comment]
Upload updated code
