### ISSUE TITLE
Teach 2 -> Bug -> ASAP

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#93]
Ray, please, check the animations in scenario and also some other changes are in red and also I tried to help with which animations to use.
Scenario https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=106009112
And that's what we got literally on 2nd command
![image](https://user-images.githubusercontent.com/36109730/46325893-6f863e80-c5c8-11e8-835d-e2938e801fdc.png)

**Comment by raynaglieri** [comment]
fixed as of our last meeting.
