### ISSUE TITLE
Teach adaptively1  -> Enhancement -> Medium-high

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#96]
G14 adjustment- could you make NPCs say "had it" in addition to raising hands? And the one who doesn't raise says "no".

https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=1091213507

**Comment by raynaglieri** [comment]
Okay, its updated.
