### ISSUE TITLE
Prob-solv.2 -> Bugs, Enhancements -> Medium, High

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#98]
Facil. log in is not working - it doesn't change from the red, although students appear and then I don't see facil channel too.
![screenshot 2018-10-23 12 48 22](https://user-images.githubusercontent.com/36109730/47376994-1a6ab380-d6c2-11e8-9793-1c60a72fb0ee.png)
Please, implement D3.
You have missed some text in G6 (in red) - please, include it.
Please, implement D15.

**Comment by raynaglieri** [comment]
I completely missed the texture updates.  The facilitator register script was set to the wrong offset. and is fixed.  The Auto-generator removed the  \n since its actually a valid formatting string. I'll add them back.

**Comment by raynaglieri** [comment]
Okay, everything should be there now!
